### ISSUE TITLE
Root access required to run script

### ISSUE THREAD

**Issue by raviv** [PATLITE-Corporation/LR6-USB_linux_python_example#1]
The script fails with the following, if ran not as root user:
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

Could you provide the required script that gives regular user permission to access the device?

Thanks!

**Comment by PATLITE-Corporation** [comment]
The specification of our sample source code is expected to be executed by root user.  Please execute with root user because there is no access authority with regular user to USB device.

Thank you.

![image](https://user-images.githubusercontent.com/86467048/216492723-224ebb0b-eb7b-4910-a116-c4f14cb60909.png)

**Comment by raviv** [comment]
Hi,

Expecting programs to be executed as root on is not realistic and is a security breach.
For the sake of other users, this is how I solved it:

You need to add a `udev` rule to allow regular users to use this device
```
echo "SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"191a\", ATTRS{idProduct}==\"8003\", MODE=\"0666\"" | sudo tee /etc/udev/rules.d/50-patlite.rules
sudo udevadm control --reload

```

(Remember to restart after that)

**Comment by PATLITE-Corporation** [comment]
Thank you for your suggestion.
